- .github/workflows/ci.yml
- .gitignore
- LICENSE
- README.md
- poetry.lock
- pyproject.toml
- scripts/gen-protos.py
- temporalio/bridge/proto/__init__.py
- tests/api/test_grpc_stub.py
* `temporalio/proto/temporal/api` -> `temporalio/api`
* `temporalio/proto/dependencies` -> `temporalio/api/dependencies`
* `temporalio/proto/temporal/sdk` -> `temporalio/bridge/proto`
* Add aliases for all protos/grpc to top-level of respective module for clarity
* Add `LICENSE`
* Add simple pure-python gRPC test
* Add `isort` to format/lint task
* Add `mypy` lint check and mypy-protobuf support
* Add `pytest` task
(carryover from #2)
> Rework grpc locations and add some different structure

- docs/conf.py
- poetry.lock
- pyproject.toml
- temporalio/client.py
- temporalio/worker.py
- temporalio/worker/__init__.py
- temporalio/worker/activity.py
- temporalio/worker/interceptor.py
- temporalio/worker/worker.py
- tests/test_worker.py
Split `temporalio/worker.py` package into multiple files in `temporalio/worker`. Also added test timeout. No real logic changed (as evident by the tests not really changing).
Preparation for workflow code which means the worker file was getting too big.
> Worker package refactor

- temporalio/bridge/Cargo.lock
- temporalio/bridge/Cargo.toml
- temporalio/bridge/src/client.rs
- temporalio/bridge/src/telemetry.rs
- temporalio/bridge/telemetry.py
- temporalio/workflow_service.py
- tests/test_workflow_service.py
Update SDK Core and PyO3
Latest changes
> Update SDK Core and PyO3

- .github/workflows/ci.yml
Added doc publishing step for Netlify similar to TypeScript.
Note that while this has a "draft docs" publish, due to relying on secrets that only works on local-repo (i.e. non-fork) PRs which we discourage. But it still has value for those and the main benefit is the "prod docs" publish.
> Add API doc publishing step

- poetry.lock
- pyproject.toml
Removed the direct grpcio dependency and rely on PyPI version still.
In issue #46, we tried to mitigate the lack of `grpcio` mac arm support by referencing a dependency directly. While this is ok during build time, it is not when uploading to PyPI:
> Invalid value for requires_dist. Error: Can't have direct dependency: 'grpcio @ https://files.pythonhosted.org/packages/61/dd/d8eda79197a1275e06621850775c7bbf34a141ff92553754dde4e87d7551/grpcio-1.46.3.tar.gz ; sys_platform == "darwin" and platform_machine
So we have removed it. Preliminary tests show this may end up building from source for `grpcio` when `pip` gets it as a dependency. This is the best we can do right now.
> Remove direct grpcio dependency

- .github/workflows/ci.yml
Fix CI Rust cache working directory
Was not caching because cargo root wasn't repo root
> Fix CI Rust cache working directory

- README.md
Added note for gRPC fix for macOS M1 users on Python 3.10+
gRPC packaging bug. Cannot fix inside the package at the moment, user has to fix post-install.
> macOS M1 Python 3.10+ gRPC README note

- README.md
Last week's 0.1a2 release added support for ARM-based (e.g., M1) Macs, but the README.md file still lists this as a missing feature, and this PR corrects it.
1. Closes 
> Remove macOS-ARM support from missing features list

- .github/workflows/ci.yml
- README.md
- poetry.lock
- pyproject.toml
- scripts/fix_wheel.py
Use `cibuildwheel` in CI now and update `grpcio` package.
* Need `cibuildwheel` at least for its Linux docker capabilities
* We get macOS and Linux arm builds out of this (note we don't build Linux arm binaries by default on PRs since they use emulation which is very slow)
* `grpcio` made a new release to fix its bad wheel naming for macOS arm builds
1. Closes #10
2. Closes #9
> Use cibuildwheel and update grpcio

- temporalio/worker/workflow_instance.py
- temporalio/workflow.py
- tests/worker/test_workflow.py
Add `get_current_history_length()` on the workflow info instance
Users need length for some continue-as-new checks. Like Go at https://github.com/temporalio/sdk-go/pull/851, we have chosen to put this as a getter on the info. We chose to use an explicit method instead of a property getter so it is clear to users this is not a property on the frozen workflow info.
> Add get_current_history_length() to workflow info

- temporalio/converter.py
- tests/test_converter.py
Added support for `IntEnum` in converter including raw int conversion _and_ type-hint-based conversion.
This is an easily serializable type in each direction. Note, a regular `Enum` is not easily serializable in each direction and will continue to fail.
> Support IntEnum in converter

- temporalio/activity.py
- temporalio/worker/activity.py
- tests/worker/test_activity.py
* Remove `activity.info().retry_policy`
* Cleanup other activity info timedelta values
* The retry policy that comes from the server for activity tasks _is not_ the one passed in when executing the activity
* Durations coming back from Core are unfortunately present-but-zero for not-present timeouts
1. Closes #62
> Remove activity info retry policy

- README.md
- pyproject.toml
- temporalio/activity.py
- temporalio/client.py
- temporalio/converter.py
- temporalio/types.py
- temporalio/worker/activity.py
- temporalio/workflow.py
- tests/worker/test_workflow.py
* Refactored to use callable protocols instead of callables where possible and moved into new `temporalio.types` package
* Support registering activity methods and calling them via `start_activity_method`, `execute_activity_method`, `start_local_activity_method`, and `execute_local_activity_method`
* Support registering activity classes and calling them via `start_activity_class`, `execute_activity_class`, `start_local_activity_class`, and `execute_local_activity_class`
Followup from #66 where we decided that instead of requiring fake instances each time you want to invoke an activity class/method, it's better to have first class support with overloads. We could not reasonably add overloads to the existing activity invocation functions without causing ambiguity that would give false …
> Type refactoring and activity class/method support

- temporalio/client.py
- tests/test_client.py
- tests/worker/test_workflow.py
Add the same high-level workflow execution description properties that TS has
Raw message is too cumbersome
> Additional high-level describe details

- temporalio/common.py
- temporalio/converter.py
- tests/worker/test_workflow.py
Change typing of search attributes to a union of lists with single types as opposed to a list of unions.
To set a search attribute to a list, you have to explicitly cast the list to be of type `List[SearchAttributeValue]` because lists are invariant and otherwise you get a mypy error. We could use `Sequence` to get around this, but I think it would be best to type as a union of list types rather than a list of unions because multiple values for the same key should be the same type anyway, otherwise ElasticSearch and maybe Temporal would probably throw an error.
1. How was this tested:
I ran mypy and the tests
> Improves typing of SearchAttributes

- temporalio/exceptions.py
- temporalio/worker/activity.py
- temporalio/worker/workflow_instance.py
- tests/test_exceptions.py
- tests/worker/test_activity.py
* Alter `ApplicationError` to prepend the type to the message if present when showing the string format
* Change workflow activation failures from `ERROR` to `WARN`
* Change activity failures from `DEBUG` to `WARN`
* Add example in test case showing how to append stack trace
1. Relates to #58
> Minor exception-related updates

- temporalio/worker/workflow_instance.py
- tests/worker/test_workflow.py
Remove completed futures from condition list
When a future would timeout, we'd still try to set its result which is a failure in asyncio
1. Closes #89
> Fix wait_condition timeout issue

- temporalio/worker/workflow_instance.py
- tests/worker/test_workflow.py
Defer execution of cancel onto the event loop so if it's received before workflow task starts, the task will be able to start and can receive the cancel
Right now we can cancel an unstarted task which doesn't catch the cancel error and doesn't allow users to react to cancel
1. Closes #91
> Fix cancel before run

- temporalio/converter.py
- tests/test_converter.py
- tests/worker/test_workflow.py
I've noticed that when executing a class activity, the type hinting was not taken into account. I've reflected this into the unit test with an additional assert.
This match the behavior of the docs where the usage is to pass the class type, not its instance:
```python
result = await workflow.execute_activity_class(
CallableClassActivity, to_add, start_to_close_timeout=timedelta(seconds=30)
)
```
Signed-off-by: Adrien Fillon <adrien.fillon@manomano.com>
`_type_hints_from_func` was not taking into account when passed with a callable class
So we can properly execute class-based activities by passing the class instead of the instance
1. Closes N/A 
2. How was this tested: Unit testing
4. Any docs updates needed? N/A
> Fix activity class type hinting when not instantiated

- README.md
- poetry.lock
- pyproject.toml
- temporalio/converter.py
- tests/test_converter.py
- tests/worker/test_activity.py
* Removed `dacite`
* Wrote custom type-hint support for deserializing
Need to support all sorts of type hints like `Optional`, `Union`, etc
1. Closes #78
> Advanced type hinting support

- README.md
In `README.md` correct a placeholder package name to the correct name used in the example. 
So that copy-pasting the example runs correctly, without modifications.
How was this tested:
* Installed python sdk.
* Ran quickstart example, making no additional modifications to the code.
* Witness `Result: Hello, my name!` as expected.
> README: Fix import name in quickstart

- .github/workflows/nightly.yml
- .github/workflows/run-bench.yml
- README.md
- poetry.lock
- pyproject.toml
- scripts/run_bench.py
- scripts/setup_bridge.py
- temporalio/worker/workflow_sandbox/importer.py
- temporalio/worker/workflow_sandbox/runner.py
* Added `scripts/run_bench.py` and a GH workflow that runs it nightly or can be manually triggered
* Updated README to clarify the cost of third-party module imports
* Fixed issue for workflows defined in `__main__` module
(if not wanting horizontal scrollbars on table, open dev console and remove `overflow` CSS property for `.markdown-body table` class...I don't feel like reworking the tables)
| workflow_count | sandbox | max_cached_workflows | max_concurrent | max_mem_mib | start_seconds | result_seconds | workflows_per_second | os      |
| -------------- | ------- | -------------------- | -------------- | ----------- | ------------- | -------------- | -------------------- | ------- |
| 100            | true    | 100                  | 100            | 64.4        | 0.2           | 3.3 …
> Add simple benchmark script

- README.md
- temporalio/converter.py
- tests/test_converter.py
Add support for string-based Enum
String-based enum is apparently widely used, along with int-based enums. Python-sdk already has a support int-based enum, and it makes sense also to support another most popular enum, string.
1. Closes #176 
Tested with updated unit test
Readme was slightly updated
> Add StrEnum conversion support

- README.md
- temporalio/converter.py
- temporalio/worker/_workflow_instance.py
- tests/test_converter.py
- tests/worker/test_workflow.py
:boom: Breaking change - now `workflow.patched()` calls always return the same boolean for the life of the workflow code. This will break users with running workflows that make multiple `workflow.patched` for the same key in the same workflow (e.g. in a loop, etc).
We were not memoizing before and people want to be able to check the same patch key at different parts of workflow code. IT was deemed acceptable to make this break while Python was in beta.
1. Relates to #143
> Memoize patched calls and support UUID conversion

- temporalio/bridge/runtime.py
- temporalio/contrib/opentelemetry.py
- temporalio/worker/workflow_sandbox/_in_sandbox.py
- temporalio/worker/workflow_sandbox/_restrictions.py
- tests/worker/workflow_sandbox/test_runner.py
* Allow imports from `concurrent.futures` (inadvertently blocked before)
* Fix type hinting inside of sandbox by using the in-sandbox workflow definition instead of outside-of-sandbox one
* Pre-initialize OpenTelemetry context at import time to prevent it lazily calling `open()` at runtime
* Use the proper `MetricsConfig` type in bridge runtime telemetry
1. Closes #201
1. Closes #200
1. Closes #199
1. Closes #198
> Sandbox and type fixes

- .github/workflows/ci.yml
Depends on https://github.com/temporalio/sdk-features/pull/162
> Add sdk-features CI trigger

- .github/workflows/ci.yml
- README.md
I like these, for helping people know what content it has, and easily jumping to a specific thing. While there is a built-in button, many don't know of it, and it's harder to get a sense of everything because it's small and scrolling.
Updatable either manually or with `npx doctoc README.md`
> Add table of contents to README

- README.md
- temporalio/activity.py
- temporalio/bridge/runtime.py
- temporalio/bridge/src/lib.rs
- temporalio/bridge/src/runtime.rs
- temporalio/exceptions.py
- temporalio/testing/_activity.py
- temporalio/worker/_activity.py
- temporalio/worker/_interceptor.py
- tests/bridge/test_runtime.py
- tests/testing/test_activity.py
- tests/worker/test_activity.py
* Throw inside sync threaded activities on cancellation using https://docs.python.org/3/c-api/init.html#c.PyThreadState_SetAsyncExc in test env and regular env
* Add ability in `@activity.defn` decorator to avoid this
* Add `activity.shield_thread_cancel_exception` context manager to have blocks shielded from this exception
* Docs and tests
1. Closes #146
> Support raising cancellation in sync multithreaded activities

- README.md
- temporalio/worker/workflow_sandbox/_importer.py
- temporalio/worker/workflow_sandbox/_restrictions.py
- temporalio/workflow.py
- tests/worker/workflow_sandbox/test_importer.py
- tests/worker/workflow_sandbox/test_restrictions.py
- tests/worker/workflow_sandbox/test_runner.py
- tests/worker/workflow_sandbox/testmodules/__init__.py
* Fix issue with `isinstance` and `issubclass` in sandbox
* Made them be thread-local during sandbox run and if in sandbox, make sure to unwrap their parameters before running
* Properly resolve relative imports to their full names for checking against passthrough/restrictions
* Add `with workflow.unsafe.imports_passed_through():` context manager for easier passthrough
* Change `SandboxRestrictions.passthrough_modules` to be a simple set of strings instead of the unnecessary full sandbox matcher used by other restrictions (💥 technically a breaking change in a marked-unstable API area)
* Added `SandboxRestrictions.with_passthrough_modules` helper to add passthrough modules to the immutable restriction set
* Did hack to make subclasses of restricted/proxy types at lease load. They still …
> Sandbox Improvements

- poetry.lock
- pyproject.toml
* Update min protobuf dependency from 3.19 to 3.20 to include https://github.com/protocolbuffers/protobuf/commit/0707f2e7f556c8396d6027d0533ec3a56d1061db
* Fix issue where `grpcio` was a dependency because the extra wasn't set right
1. Closes #226
2. Closes #224
> Update min proto version and fix gRPC optional dependency

- README.md
- temporalio/client.py
- temporalio/common.py
- temporalio/worker/_activity.py
- tests/helpers/__init__.py
- tests/worker/test_activity.py
- tests/worker/test_workflow.py
* Properly support `Optional` params in workflows/activities
* Make sure that we don't try to send cancelled error to server on worker shutdown (was only caused by the recent #217)
* Updated README to note that generic types are not resolved for purposes of deserialization
* Updated README to properly use `asyncio.create_task` for calls to `asyncio.wait` since 3.11 requires that now
1. Closes #232
2. Closes #234
3. Closes #236
4. Closes #237
> Minor type improvements

- .github/workflows/ci.yml
Waiting on https://github.com/temporalio/sdk-features/pull/207
> Rename sdk-features to features"

- README.md
- temporalio/worker/_activity.py
- temporalio/worker/_worker.py
- tests/worker/test_activity.py
When using sync activities, if the thread pool or process pool executor breaks irrecoverably, we now fail the entire worker.
1. Closes #245
> Fail activity worker on broken executor

- temporalio/common.py
This PR adds the missing `TERMINATE_IF_RUNNING` option to the existing `WorkflowIDReusePolicy` enum.
So that users of the SDK can use the easily accessible enum value, instead of hardcoding the value `4` or reaching for the longer import `temporalio.api.enums.v1.WorkflowIdReusePolicy.WORKFLOW_ID_REUSE_POLICY_TERMINATE_IF_RUNNING`.
1. How was this tested:
No special tests, that is an enum.
2. Any docs updates needed?
I haven't found any documentation to update.
> Add missing option to `WorkflowIDReusePolicy` enum

- README.md
- temporalio/converter.py
- tests/test_converter.py
* Added new concept called `JSONTypeConverter` for those wanting to use existing JSON converter but customize the conversion from untyped JSON objects to expected type-hinted values.
* Added (large) new README section on data conversion for custom types
1. Closes #264
> Add JSONTypeConverter

- poetry.lock
- pyproject.toml
> Change types-protobuf dependency spec to match protobuf

- README.md
- temporalio/client.py
- temporalio/worker/_activity.py
- temporalio/worker/_workflow_instance.py
- temporalio/worker/workflow_sandbox/_restrictions.py
- tests/worker/test_activity.py
- tests/worker/test_workflow.py
* Disallow non-instances as activities
* Add proper query list to end of exception
* Make "None" result as null for async activity completion
* Improve workflow sandbox suggestions
* Update quick start to suggest putting workflows in separate file
* Improve clarity of error message on restricted workflow access
* Add above error message to README for better SEO
* Clarify that `heartbeat_timeout` is needed on caller side when wanting heartbeat/cancellation for activities (even if not technically _required_)
1. Closes #228
2. Closes #265
3. Closes #266
4. Closes #273
5. Closes #282
> Minor updates

- scripts/fix_wheel.py
Wheels used to be properly created with `cp37-abi3-macosx_10_0_x86_64` tag but have now changed to `cp37-abi3-macosx_12_0_x86_64`.
We added some fix-wheel code to change this back. However new pip on macOS doesn't support the `10_0` tag, only as low as `10_4`, so we set it to `10_9` which is something we have seen other projects do.
Now all Intel macOS users using Python >= 3.7 and macOS >= 10.9 can work with this wheel.
> Fix macOS x86_64 wheel tag

- .github/workflows/build-binaries.yml
- .github/workflows/ci.yml
- temporalio/converter.py
- tests/test_converter.py
Properly call JSON type converters recursively. Also fixate the Poetry version in CI due to Poetry bug.
1. Closes #289
> Call JSON type converters recursively

- README.md
- temporalio/worker/__init__.py
- temporalio/worker/_workflow_instance.py
- temporalio/workflow.py
* Discourage use of activity ID (fixes #293)
* Expose `WorkflowReplayResult` and `WorkflowReplayResults` properly (fixes #285)
* Document gevent incompatibility (fixes #291)
> Minor doc update

- temporalio/bridge/runtime.py
- temporalio/bridge/src/runtime.rs
- temporalio/runtime.py
This PR adds python representation of `global_tags` and passes them through to rust version
See https://github.com/temporalio/sdk-core/pull/518 for the base PR in the core SDK. This PR just adds means to set the new parameter from Python
The result should allow us to identify resources reporting metrics (i.e. service name, host ID, environment, etc)
1. Closes (closed the issue in sdk-core. Doesn't seem to be one here)
Tested in the original PR
Unlikely (unless we document telemetry fields somewhere)
**Note:** I bumped the `sdk-core` submodule to current `master`. The project does not build with that version (and did not seem to build even before I touched it). I did my tests with my work applied on top of the commit referenced in the …
> Pass through global telemetry tags

- temporalio/client.py
- tests/test_client.py
- tests/worker/test_workflow.py
* Remove warning saying schedules are experimental
* Add check that requires limited actions be true on create when remaining actions are non-zero and vice-versa
1. Closes #320
1. Closes #316
> Remove experimental tag for schedules and add limited action check

- temporalio/bridge/src/lib.rs
- temporalio/bridge/src/testing.rs
- temporalio/bridge/testing.py
- temporalio/client.py
- temporalio/testing/_workflow.py
- tests/conftest.py
- tests/worker/test_workflow.py
* Use latest Temporal server for `WorkflowEnvironment.start_local` via CLI dev server instead of Temporalite
* Removed the `temporalite_` options from `WorkflowEnvironment.start_local` that were clearly documented they may be removed
* Since we're on a new server, altered `ScheduleRange` `step` and `end` fields to default to what they default to on the server
* Updated tests
1. Closes #272
> Move from Temporalite to Temporal CLI dev server

- temporalio/bridge/src/worker.rs
- temporalio/bridge/worker.py
- temporalio/client.py
- temporalio/worker/_replayer.py
- temporalio/worker/_worker.py
- tests/helpers/__init__.py
- tests/test_client.py
- tests/worker/test_worker.py
Add support for new worker versioning feature
Parity
1. Closes https://github.com/temporalio/sdk-python/issues/335
Added tests
Yes to follow
> Worker Versioning

- temporalio/client.py
- tests/worker/test_worker.py
Realized this got missed while doing .NET
> Reachability type wasn't passed through all the way

- .github/workflows/ci.yml
- README.md
- temporalio/activity.py
- temporalio/client.py
- temporalio/common.py
- temporalio/converter.py
- temporalio/testing/_activity.py
- temporalio/worker/_activity.py
- temporalio/worker/_workflow.py
- temporalio/worker/_workflow_instance.py
- temporalio/workflow.py
- tests/test_common.py
- tests/test_converter.py
- tests/test_workflow.py
- tests/worker/test_activity.py
- tests/worker/test_workflow.py
* Add a `temporalio.common.RawValue` class which represents a raw payload that is never converted (but still encoded/decoded)
* Update composite/default payload converter to pass through that type by default
* Add `dynamic=True` for `@workflow.defn` which requires the run method to accept a single `Sequence[RawValue]` param
* Add `dynamic=True` for `@activity.defn` which requires the function to accept a single `Sequence[RawValue]` param
* Updated `@workflow.signal` to work with `Sequence[RawValue]` args and deprecate/warn when using the existing style (which was varargs of already-converted values which makes little sense)
* Updated `@workflow.update` to work with `Sequence[RawValue]` args and deprecate/warn when using the existing style (which was varargs of already-converted values …
> Dynamic workflows, activities, signals, and queries

- README.md
The blog post is essential reading for anyone interested in understanding the codebase, so I think a link from the repo README makes sense. But if it is confusing to have more links up at the top then it could also go lower down, in the "Development" section.
> Link to Python SDK launch blog post

- README.md
- temporalio/worker/_workflow_instance.py
- temporalio/workflow.py
- tests/testing/test_workflow.py
- tests/worker/test_workflow.py
* Deprecated `async def` queries
* Raise a read-only-context error for doing anything invalid in a query (and it's also ready for update validators when we get there)
1. Closes #250
> Deprecate async def queries and disallow most workflow operations in read-only context

- temporalio/contrib/opentelemetry.py
Added span kinds for TracingInterceptor
Now, all **START** actions are **opentelemetry.trace.SpanKind.CLIENT**
and all **RUN** actions are **opentelemetry.trace.SpanKind.SERVER**
For other actions kind=INTERNAL 
Before this changes all spans was **INTERNAL**, so it was unavailable to build service graphs for APM (ex.: Grafana Tempo)
For example, this is the service graph with INTERNAL spans:
And this is for CLIENT/SERVER:
Spans attributes now look like this:
All experiments located [here](https://github.com/northpowered/temporal-otlp)
This repo is a bit raw now, and hasn\`t good README, but it`ll be fixed soon
1. Closes #357 
SDK developers reccomended testing, Integration tests were made [here](https://github.com/northpowered/temporal-otlp)
3. Any docs updates …
> Provide Span.Kind for TracingInterceptor

- temporalio/worker/_workflow_instance.py
- temporalio/workflow.py
- tests/conftest.py
- tests/worker/test_workflow.py
* Added `get_history_size()` and `is_continue_as_new_suggested()` to `workflow.info()`
* Added test to confirm behavior
> Expose history size and continue-as-new-suggested

- temporalio/testing/_workflow.py
- tests/testing/test_workflow.py
Stop overriding user interceptors in testing environment (was using wrong variable)
1. Closes #363
> Fix interceptors in testing environment

- temporalio/converter.py
This commit enables the `JSONProtoPayloadConverter` to accept `ignore_unknown_fields` as an optional argument so that we can utilize this functionality when converting proto to json.
When deploying multiple services out-of-sync with Temporal, proto fields may change in a way that would not necessarily cause the workflow to fail, however without setting the `ignore_unknown_fields` option above, otherwise backwards-compatible proto changes result in conversion errors. As mentioned in the linked issue below, "People may want to ignore unknown fields and right now they have to remake the class themselves"
1. Closes https://github.com/temporalio/sdk-python/issues/315
- Spinning up a worker / workflow that accept an initial version of proto args
- Changing the proto …
> Allow JSONProtoPayloadConverter to accept `ignore_unknown_fields` as an optional argument

- temporalio/worker/_activity.py
- temporalio/worker/_worker.py
On shutdown, wait on all activities to complete including their completion futures to core. In core, shutdown may complete but calls to server may still be outstanding. So in the case of #368 where the process was killed when shutdown completed, the completion may have happened but not flushed causing server to not get the completion.
There is no good/easy way to test the internal core difference between activity completion sent and activity completion flushed.
1. Closes #368
> Wait for activity completions on worker shutdown

- temporalio/bridge/Cargo.lock
- temporalio/bridge/Cargo.toml
- temporalio/bridge/runtime.py
- temporalio/bridge/src/client.rs
- temporalio/bridge/src/runtime.rs
- temporalio/bridge/src/worker.rs
- temporalio/runtime.py
- temporalio/worker/_workflow_instance.py
* Update core
* Update cargo deps including bumping tonic to 0.9
* Update Rust bridge to adopt new metric instantiation
* Add missing metrics options
* 💥 BREAKING CHANGE - Removed `temporalio.runtime.TelemetryConfig.tracing` and associated class
* This is only for advanced internal support for core tracing which wasn't really used anyways
1. Closes #371
> Update core/tonic, update metric options, remove core tracing

- temporalio/activity.py
- temporalio/bridge/metric.py
- temporalio/bridge/src/lib.rs
- temporalio/bridge/src/metric.rs
- temporalio/common.py
- temporalio/runtime.py
- temporalio/testing/_activity.py
- temporalio/worker/_activity.py
- temporalio/worker/_replayer.py
- temporalio/worker/_worker.py
- temporalio/worker/_workflow.py
- temporalio/worker/_workflow_instance.py
- temporalio/workflow.py
- tests/helpers/__init__.py
- tests/test_runtime.py
- tests/worker/test_workflow.py
* Added `MetricMeter`, `MetricCounter`, `MetricHistogram`, and `MetricGauge` as (abstract) classes to `temporalio.common`
* Added `metric_meter` property to `temporalio.runtime.Runtime`
* Added `temporalio.workflow.metric_meter()` function to get replay-safe metric meter
* Added `temporalio.activity.metric_meter()` function to get optional metric meter
* NOTE: This does not return a metric meter for sync activities that are non-threaded (i.e. multiprocess) because a meter cannot be shared across processes and it's a large effort to support metric shipping across processes for this rarely used activity type
* Added `metric_meter` attribute to `temporalio.testing.ActivityEnvironment` that defaults to noop impl
* API docs and tests
Handles part of #369
> Custom metric support

- temporalio/worker/_workflow_instance.py
Explicitly include the error object in the `logger.warning` call after failure to activate on a workflow.
If the log call happens outside any `except` block and `exc_info` is just set to `True` no error information is included in the log (making it difficult to understand what caused the error).
> Fix logging of error on activation failure

- temporalio/bridge/Cargo.lock
- temporalio/bridge/metric.py
- temporalio/bridge/runtime.py
- temporalio/bridge/src/lib.rs
- temporalio/bridge/src/metric.rs
- temporalio/bridge/src/runtime.rs
- temporalio/bridge/src/worker.rs
- temporalio/runtime.py
- tests/worker/test_workflow.py
Support for user-retrieved metrics via a buffer
* Added Rust code to support metric buffer including ensuring the same Python metric/attribute objects are reused
* Added `MetricBuffer`, `BufferedMetric`, and `BufferedMetricUpdate` to `temporalio.runtime`
1. Closes #369
> Buffered metrics

- temporalio/bridge/client.py
- temporalio/bridge/src/client.rs
- temporalio/client.py
- temporalio/service.py
Added `temporalio.service.KeepAliveConfig` and parameters for connection, defaulting to 30s interval w/ 15s timeout but also allowing disabling.
There's not a great way to unit test this without slowing down unit tests
1. Closes #395
> Client keep alive support

- .github/workflows/ci.yml
- README.md
- tests/test_client.py
- tests/testing/test_workflow.py
* Document that there's a gevent sample
* Document that time-skipping test server doesn't work on ARM
1. Closes #59
1. Closes #379
> README updates and CI fixes

- temporalio/client.py
- tests/test_client.py
Added `start_delay` to `start_workflow` and `execute_workflow`
1. Closes #404
> Workflow start delay

- temporalio/client.py
- tests/test_client.py
Remove poll update interceptor & timeout on result
Per discussed changes
1. Closes https://github.com/temporalio/sdk-python/issues/409 and closes https://github.com/temporalio/sdk-python/issues/408
> Update last cleanup items

- temporalio/client.py
Bring docstring into line with implemented polling behavior.
> Fix Workflow Update result docstring

- scripts/fix_wheel.py
Update the Temporal PYD file on Windows to the proper name after it got changed by a recent library update.
This seems to be caused by a setuptools-rust update ([this comment](https://github.com/PyO3/setuptools-rust/pull/352#discussion_r1293444464) explains what we're seeing and CI started failing on that release). Hopefully a wholesale update of our build processes in #398 will fix this.
> Fix Windows CI binary build fix

- temporalio/worker/_workflow_instance.py
- tests/worker/test_workflow.py
Fixed some bugs in search attrib upsert that occur if the workflow has no initial search attribs
Bugs bad
1. Closes 
Added simple test
> Fix bugs in upsert search attribs

- temporalio/workflow.py
- tests/worker/test_workflow.py
Now, `workflow.LoggingAdapter` overrides `isEnabledFor`, which does not add additional stack frame during logging, instead of `log`.
To have correct line numbers in logs.
1. Closes #447
Unit test
No
> Fix line number in workflow.logger

- temporalio/types.py
Since pyright 1.1.344, my code stated to fail with errors such as the following:
```bash
webapp.py:46:22 - error: No overloads for "execute_workflow" match the provided arguments (reportGeneralTypeIssues)
webapp.py:47:22 - error: Argument of type "(self: HelloWorkflow, name: str) -> Coroutine[Any, Any, str]" cannot be assigned to parameter "workflow" of type "str" in function "execute_workflow"
  "function" is incompatible with "str" (reportGeneralTypeIssues)
```
The code being something like:
```python
@workflow.defn(name="HelloWorkflow")
class HelloWorkflow:
@workflow.run
async def run(self, name: str) -> str:
return await workflow.execute_activity(
hello_activity,
HelloParams("Hello", name),
start_to_close_timeout=timedelta(seconds=10),
)
return await env.temporal.execute_workflow( …
```
> Fix typing of methods for pyright

- scripts/gen_protos.py
This is just a minor reorganization of the `gen-protos` script (done while modifying the script for something else). The diff is largely indentation, so is easiest to understand with [whitespace ignored](https://github.com/temporalio/sdk-python/pull/465/files?w=1).
Compared `poe gen-protos` output.
> Minor reorganization of gen-protos script

- temporalio/worker/_workflow.py
- tests/worker/test_workflow.py
Add a couple of https://github.com/temporalio/rules references as error prefixes
> Prefix some errors with rule identifiers

- temporalio/worker/_workflow.py
Today if we receive an activation with a cache-remove job, we complete the activation in core and _then_ remove the workflow from cache. That's bad. There is the potential for a rare bug where:
* Python receives activation
* Activation takes too long causing server-side task timeout causing server to send new task which core buffers while current activation is in flight
* Already-timed-out-server-side activation completion is sent to core
* Core sends eviction activation and Python sends activation completion _before_ removing from cache
* Core sends the buffered task to run from beginning, but it reuses cache from old eviction activation because the eviction code wasn't reached just yet
This moves eviction processing to before activation completion. Also, this adds optimizations to not …
> Apply eviction before completing activation

- temporalio/types.py
Explicitly specify `__arg` is a position argument in `Method*SingleParam` types.
After updating pyright from 1.1.338 to 1.1.348 (following pylance release cycle), type check and inference related to `client.execute_workflow` and `workflow.execute_activity` are failing because of parameter name mismatch with `__arg`. Causing pyright rejecting the correct overloads.
This can be reproduced with the code sample in the collapsed block. Trying to guide pyright with type hinting on `MethodAsyncSingleParam` shows why the overload got rejected. The problem is "Parameter name mismatch"
I guess python sdk won't use the method types by keyword but only use them with position argument. So this change signal the sdk's intent to type checker.
After adding the last `/` in the type pyright is passing. …
> Fix SingleParam types for pyright checking

- temporalio/worker/_worker.py
Flagged MD5 as not used for security.
MD5 algorithm is not allowed under FIPS requirements due to security concerns. Temporal SDK uses MD5 for non-security related reasons, and so it should be flagged as such.
1. How was this tested:
We've been monkey-patching this (or using sed on python file directly after installation) up till now.
> Flag MD5 as non-security related usage for FIPS compatibility

- temporalio/bridge/worker.py
- tests/worker/test_workflow.py
Make updates get run through data converters
Kind of important. Maybe people want to encrypt stuff.
1. Closes https://github.com/temporalio/sdk-python/issues/477
Added updates to custom encoder test
> Ensure update input and responses are run through converters

- temporalio/workflow.py
> Fix execute_child_workflow apidoc

- temporalio/bridge/Cargo.lock
- temporalio/bridge/Cargo.toml
- temporalio/bridge/client.py
- temporalio/bridge/src/client.rs
- temporalio/client.py
- temporalio/service.py
- tests/api/test_grpc_stub.py
Implements https://github.com/temporalio/features/issues/426
* Add `api_key` option to `Client` constructor
* Add `api_key` property (including setter) to `Client`
These will set the "Authorization" header with the key prepended with "Bearer ". This leverages https://github.com/temporalio/sdk-core/pull/699.
1. Closes #482
> API key client option

- temporalio/client.py
Remove experimental flag from start_delay
Remove experimental flag from start_delay
To indicate the current state of start_delay workflow option.
> Remove experimental flag from start_delay

- .github/workflows/ci.yml
- temporalio/bridge/Cargo.lock
- temporalio/bridge/client.py
- temporalio/bridge/src/client.rs
- temporalio/client.py
- temporalio/service.py
* Updated core
* Added `temporalio.service.HttpConnectProxyConfig`
* Updated client to accept that config
Note: This tests against the https://github.com/temporalio/features/tree/http-connect-proxy-python branch of the features repo to ensure it works. That branch contains a not-yet-merged Python feature test for proxy.
> HTTP CONNECT proxy support

- temporalio/worker/_workflow_instance.py
- tests/worker/test_workflow.py
* Add `temporal_workflow` extra data on workflow task failure logs
* Add test to ensure workflow/activity task failures have extra data
1. Closes #500
> Ensure extra data on task fail logs

- README.md
- temporalio/bridge/src/worker.rs
- temporalio/bridge/worker.py
- temporalio/worker/_replayer.py
- temporalio/worker/_worker.py
- temporalio/worker/_workflow.py
- temporalio/worker/_workflow_instance.py
- temporalio/worker/workflow_sandbox/_in_sandbox.py
- temporalio/worker/workflow_sandbox/_runner.py
- temporalio/workflow.py
- tests/helpers/__init__.py
- tests/test_workflow.py
- tests/worker/test_workflow.py
* Added `workflow_failure_exception_types` to `Worker` to allow configuring failure exception types at a worker level
* Added `failure_exception_types` to `@workflow.defn` to allow configuring failure exception types at a workflow level
* Updated bridge code to include worker-level and workflow-type-level non-determinism-as-fail based on the presence of `temporalio.workflow.NondeterminismError` (or super type) in worker/workflow options
* Documented in README, API doc, and marked experimental
* Several tests for several scenarios
It's no coincidence this mimics https://github.com/temporalio/sdk-dotnet/pull/205. Also see the feature issue at https://github.com/temporalio/features/issues/322.
1. Closes #446
> Ability for certain task failure types to fail workflow

- temporalio/bridge/src/worker.rs
- temporalio/bridge/worker.py
- temporalio/worker/_worker.py
- tests/worker/test_workflow.py
* Update core to get https://github.com/temporalio/sdk-core/pull/721
* Added `client` property on `Worker` w/ getter/setter
* Setter now replaces the worker client
* Added test proving the worker switches servers (even if this is not how people should use client replacement)
1. Closes #513
> Worker client replacement

- temporalio/bridge/worker.py
- tests/worker/test_workflow.py
Fixed issue where if the same payload was returned from a codec, we were clearing metadata it before applying new metadata, naively/incorrectly assuming that it wouldn't be the same reference. Fixed to use `CopyFrom` which checks reference.
1. Closes #525
> Fix issue with codecs returning passed-in payloads

- .github/workflows/ci.yml
- temporalio/worker/_workflow_instance.py
- tests/worker/test_workflow.py
* Set `workflow.unsafe.is_replaying()` to `True` during eviction
* Raise a special `BaseException`-based exception during eviction instead of `RuntimeError` which has an `Exception` base
1. Closes #523
> During eviction, set is_replaying and raise special exception

- .github/workflows/ci.yml
- temporalio/client.py
- temporalio/worker/_workflow_instance.py
- tests/worker/test_workflow.py
* Always send `id` to server on update (SDK side defaults to `uuid4()`)
* Added `temporalio.client.WorkflowUpdateWaitStage` enumerate that maps to the gRPC equivalent
* Added required `wait_for_stage` parameter to `Client.start_update`. Disallow `ADMITTED` at runtime.
* Added `WorkflowHandle.get_update_handle` and `WorkflowHandle.get_update_handle_for`. These accept a run ID, but default to one on the handle
* Updated start update polling to poll until stage reached or ACCEPTED. If more polling needed, switches to result polling.
Don't wait on feature repo CI to pass before reviewing. I will create a feature repo branch to fix that.
1. Closes #424
1. Closes #484
1. Closes #485
1. Closes #514
> Required wait update stage, update polling improvements, and other update changes

- temporalio/worker/_workflow.py
- temporalio/worker/_workflow_instance.py
- temporalio/worker/workflow_sandbox/_runner.py
- tests/helpers/__init__.py
- tests/worker/test_workflow.py
Wrapped tasks in list when gathering stack trace so that anything affecting task set during doesn't affect trace. Also added another deadlock test for this scenario, shrunk deadlock timeout in worker to 1 during test, fixed minor sandbox issue, and made minor change to error message on eviction failure.
1. Closes #527
> Allow proper stack trace on eviction deadlock

- README.md
- temporalio/worker/workflow_sandbox/_restrictions.py
- temporalio/workflow.py
- tests/helpers/worker.py
- tests/worker/test_workflow.py
- tests/worker/workflow_sandbox/test_runner.py
`asyncio.as_completed` and `asyncio.wait` are non-deterministic sometimes so we need alternatives.
* Created deterministic `workflow.as_completed` and `workflow.wait` alternatives
* Updated the README to encourage their use
* Issue [warnings](https://docs.python.org/3/library/warnings.html) when the asyncio ones are called (to become errors in #535 in the future)
1. Closes #429
1. Closes #518
> Add deterministic alternatives for asyncio.wait and asyncio.as_completed

- .github/workflows/build-binaries.yml
- .github/workflows/ci.yml
- .github/workflows/run-bench.yml
- Updated all GHA actions to latest.
- GitHub is pulling the plug on `download-artifact@v2` and `upload-artifact@v2` on June 30th;
- `actions-rs/toolchain@v1` is no longer maintained;
- All GHA official actions based on Node 16 are deprecated.
> Bump GitHub Actions

- .github/workflows/build-binaries.yml
- .github/workflows/ci.yml
- .github/workflows/run-bench.yml
- Fix options on GHA `swatinem/rust-cache@v2`, because I forgot to make adjustment while updating from `@v1` in previous PR.
> Fix GHA config for swatinem/rust-cache@v2

- temporalio/worker/_workflow_instance.py
- temporalio/workflow.py
- tests/worker/test_workflow.py
* Added `temporalio.workflow.UpdateInfo`, similar to `temporalio.workflow.Info`, with workflow-accessible information for an update (currently `id` and `name`)
* Added `temporalio.workflow.current_update_info()`, similar to `temporalio.workflow.info()`, with the current in-context update info
* This uses `contextvars` so it works inside the handler and things it starts but nowhere else
* `current_update_info()` is preferred over `info()` because the latter is always present and there is nothing "current" about it, whereas the former can return `None` if you're not in an update
1. Closes #542
> Access current update info with ID inside update handler

- temporalio/common.py
- tests/test_client.py
* Fix schedule test assertions that expect certain num actions on backfill (backfill logic changed in 1.24)
* Fix schedule test assertions that expect untyped search attributes (search attributes for scheduled workflows are mapped to proper types in 1.24)
* Fix issue found during schedule test assertions where we were improperly checking against a shadowed variable when appending search attributes
> Server 1.24 related fixes

- .github/workflows/run-bench.yml
- Install protoc in run-bench CI job. It is required since #547.
> Install protoc in run-bench CI job

- pyproject.toml
- temporalio/worker/_workflow_instance.py
- temporalio/workflow.py
- tests/worker/test_workflow.py
Closes #538
Implementation ready for review; names are still under discussion.
- Added a new API to wait for update and signal handler executions to complete. Provisionally named `workflow.all_handlers_finished()`.
- Issue warnings on workflow exit if any handlers are unfinished.
- Allow warnings to be disabled on a per-handler basis via a signal/update decorator parameter.
Workflows exiting while handler executions are in progress is an important category of run-time workflow incorrectness.
> New API to wait for handler executions to complete and warnings on unfinished handler executions

- temporalio/bridge/Cargo.lock
- temporalio/bridge/Cargo.toml
- temporalio/bridge/src/runtime.rs
- temporalio/bridge/src/worker.rs
- temporalio/bridge/worker.py
- temporalio/worker/__init__.py
- temporalio/worker/_replayer.py
- temporalio/worker/_tuning.py
- temporalio/worker/_worker.py
- tests/worker/test_worker.py
Expose resource based auto-tuner
Adding in all SDKs
1. Closes 
Added some tests, manual verification with omes / existing core tests
Will be after experimental phase
> Expose resource based auto-tuner options

- temporalio/worker/_workflow_instance.py
very small fix to optimize loading sources from files, not sure how it slipped my mind in the initial feature.
Added a few type annotations and now check for membership of the map by using `filename not in sources.keys()`.
> micro-pr: skip files that are already mapped for enhanced stack traces

- temporalio/client.py
- temporalio/common.py
- tests/worker/test_workflow.py
* Added `id_conflict_policy` to workflow start/execute and added test
1. Closes #504
> Support for workflow ID conflict policy

- tests/worker/test_workflow.py
`pytest.raises()` scope should be limited to the statement that raises only.
This PR fixes a couple of bugs (mine) in test assertions and improves style in others that were not incorrect (other peoples').
> Use minimal scope with pytest.raises

- temporalio/client.py
- tests/test_client.py
Support query for listing schedules
1. Closes #573
> Support query for listing schedules

- poetry.lock
- pyproject.toml
Cibuildwheel was using old manylinux image, just had to update cibuildwheel itself. This was tested for build binary while this PR was in draft mode.
1. Closes #577
> Fix old manylinux image issue via cibuildwheel update

- temporalio/activity.py
This PR updates the lazy loading behavior for activity `_logger_details` so that activity details will be included in logging outputs even if not preloaded by adding to message.
Solution identified/proposed by @cretz  in this Issue: https://github.com/temporalio/sdk-python/issues/592
Desire to allow activity logs to include extra information without adding them to the message string.
1. Closes  592
2. How was this tested:  Manually running logs
3. Any docs updates needed? No
> Updated lazy loaded logger_details

- temporalio/bridge/Cargo.lock
- temporalio/worker/_workflow_instance.py
- tests/worker/test_replayer.py
- tests/worker/test_replayer_command_reordering_backward_compatibility.json
- tests/worker/test_workflow.py
Fixes https://github.com/temporalio/sdk-python/issues/528
With this change we honor all non-completion commands emitted by workflow coroutines, even if they come after a completion command (i.e. complete/CAN/cancel/fail). A consequence is that when an update completion is returned in the same WFT response as a workflow completion, the client will always get the update response; previously that was only the case if the update handler returned prior to any completion command being emitted by another coroutine.
The solution involves devolving responsibilites for this logic to core: see explanatory code comments in https://github.com/temporalio/sdk-core/pull/776.
```
$ pytest -k "completion" tests/worker/test_workflow.py
tests/worker/test_workflow.py::test_update_completion_is_honored_when_aft …
```
> Honor all non-completion commands

- .github/workflows/ci.yml
Adding omes worker image build to all SDKs
> Add omes image build

- temporalio/worker/_workflow_instance.py
- tests/worker/test_workflow.py
Before this change, the Python SDK added commands on the activation completion before payload conversion and then filled them out including with conversion. This meant that in cases where the payload converter caused a application error (or was caught), the command would be half created/filled-in and you'd get errors like "invalid TaskQueue on ScheduleActivityTaskCommand: missing task queue name".
Now, in multiple places, we do the payload conversion before command creation/addition which allows exceptions to occur before the command is added.
1. Closes #540
1. Closes #564
> Create commands after payload conversion

- temporalio/converter.py
- temporalio/exceptions.py
- tests/worker/test_activity.py
- tests/worker/test_workflow.py
Fixes #468
Support setting `next_retry_delay` when raising `ApplicationError` from activity code.
PR contains an integration test.
> Support activity retry delay

- temporalio/worker/_workflow_instance.py
- tests/worker/test_workflow.py
Closes https://github.com/temporalio/sdk-python/issues/584
- Add the `[TMPR1102]` rule tag to the warning messages
- Add tests confirming that the `all_handlers_finished` and warnings logic work for continue-as-new, dynamic handlers, and late-registered handlers.
- Refactor all tests as a `pytest.mark.parametrize` Cartesian product
> Unfinished handlers: add rule and test CAN, dynamic, and late-registered handlers

- temporalio/client.py
- tests/test_client.py
Fixes #624
This is a bug identified by pyright type checking.
- PR includes two commits: a test that fails on `main` before the fix, and the fix.
I also confirmed manually that if the server responds with gRPC error `ALREADY_EXISTS`, but the error details do not satisfy the logic in the SDK code, then the user gets
```
UnboundLocalError: cannot access local variable 'resp' where it is not associated with a value
```
What they should get is `temporalio.service.RPCError`.
> Fix exception-swallowing code path

- temporalio/worker/_workflow.py
- temporalio/worker/_workflow_instance.py
- temporalio/worker/workflow_sandbox/_runner.py
- tests/worker/test_workflow.py
Remade the PR to resolve a few issues.
See https://github.com/temporalio/sdk-python/pull/595 for full discussion on this issue.
> Include stack trace on deadlock detection exception (re)

- temporalio/bridge/Cargo.lock
Ran `cargo update -p quinn-proto` to update the quinn-proto version in Cargo.lock
Pick up security vulnerability fix
1. Closes #642
> Upgrade quinn-proto version to fix security vulnerability

- temporalio/bridge/Cargo.lock
```bash
cd temporalio/bridge && cargo update tonic --precise 0.12.3
```
Pulls in fix for CVE-2024-47609, which has started showing up in our container scanner reports.
> Upgrade tonic to v0.12.3 to fix security vulnerability

- temporalio/client.py
- tests/test_client.py
Don't ask for immediate trigger when a backfill is requested, and don't ask for a backfill when an immediate trigger is requested.
Closes #678.
> Fix logic bug in create_schedule() re. backfills

- temporalio/worker/_tuning.py
Realized I missed this when translating to C#
> Slot info should be optional on release context

- temporalio/client.py
- tests/worker/test_workflow.py
Prior to this PR, update requests were not using the `first_execution_run_id` returned by StartWorkflow. This meant that, in a situation where workflow IDs are beign re-used, a stale workflow handle from a closed workflow could accidentally be used to send an update to the wrong workflow execution.
> Update bug fix: prevent update from a stale workflow handle

- temporalio/client.py
- temporalio/workflow.py
- tests/worker/test_update_with_start.py
- tests/worker/test_workflow.py
Bug fix: Under Update-with-start, neither update nor workflow client-side results were honoring the result type passed by the user or obtained from type annotations. This meant that dataclasses were being returned as dicts.
> Fix uws client-side result types

- tests/worker/test_replayer.py
- tests/worker/test_replayer_event_tracing.json
- tests/worker/test_replayer_event_tracing_alternate.json
- tests/worker/test_replayer_event_tracing_double_sig_at_start.json
- tests/worker/test_workflow.py
Copying tests from https://github.com/temporalio/sdk-python/pull/717 since they are useful even though we're not going to be making those changes
> Useful event ordering tests from discarded changes to event loop

- .github/workflows/ci.yml
- pyproject.toml
In general, CI test logs should:
- Make it easy to see which tests have failed
- Help understand how they have failed
To that end, they should:
- Include minimal output for tests that pass
- Include full output for tests that fail (should not be many)
Previously we were using pytest's `log-cli` feature, which outputs logs for all tests as the tests are run. This PR stops using that, instead switching to a config that outputs all logging output >= DEBUG for failed tests, at the end of the test run (search for `=================================== FAILURES ===================================`).
See https://docs.pytest.org/en/stable/how-to/logging.html#logging.
> More precise logging in CI

- tests/helpers/__init__.py
- tests/worker/test_workflow.py
Fixes #554
Add tests confirming that `asyncio.Lock` and `asyncio.Semaphore` can be used in workflow code to control concurrency of coroutines (tasks spawned by the main coroutine, and update handlers).
The fact that these tests pass largely follows from the fact that our event loop implementation  has functioning implementations of `call_later()` `call_soon()`, so these tests could alternatively be moved into the `features` repo, as part of a feature test confirming that all languages have mutex/semaphore primitives that can be used for this sort of workflow concurrency control.
> Add tests of asyncio.Lock and asyncio.Semaphore usage

- pyproject.toml
- temporalio/workflow.py
- tests/test_workflow.py
Fixes #689 
This PR causes the workflow decorator to raise an exception if the workflow definition contains an (update, validator) pair with inconsistent signatures. The exception will therefore be raised at import time when running a workflow worker. We re-use the same definition of "inconsistent signatures" that we use when comparing the `@workflow.run` and workflow `__init__` methods. We already had type-checking for this, but we lacked a run-time check; an exception would have been raised eventually, but at update validation time.
> Run-time check for update validator signature

- temporalio/worker/_activity.py
- temporalio/worker/_workflow_instance.py
- tests/worker/test_workflow.py
Fixed an issue where the `application_failure_info` wasn't being set when failing to convert failures
1. Closes #685
> Fix issue when failing to convert failure

- README.md
- temporalio/worker/workflow_sandbox/_importer.py
- temporalio/worker/workflow_sandbox/_restrictions.py
- tests/worker/workflow_sandbox/test_importer.py
* Added `passthrough_all_modules` dataclass field to `temporalio.worker.workflow_sandbox.SandboxRestrictions` class, defaulted to false that, when set to true, will be as if all modules are passed through
* Added `with_passthrough_all_modules` helper method to that same class to return a new instance with that value set to true
* Some README updates clarifying this new setting
1. Closes #691
> Support passing through all modules

- temporalio/bridge/runtime.py
- temporalio/bridge/src/runtime.rs
- temporalio/runtime.py
Tested using
```
docker run \
-p 127.0.0.1:4317:4317 \
-p 127.0.0.1:4318:4318 \
-p 127.0.0.1:55679:55679 \
otel/opentelemetry-collector-contrib:0.118.0
```
and running https://github.com/temporalio/samples-python/blob/main/open_telemetry/README.md
using
```
Runtime(
telemetry=TelemetryConfig(
metrics=OpenTelemetryConfig(
url="http://localhost:4318/v1/metrics", http=True
)
)
)
```
> Expose http option for OTLP

- tests/worker/test_workflow.py
This is one cause of flakes. I believe this change is from incorrect to correct.
> Do not include `self` parameter in handlers in test

- temporalio/worker/_workflow_instance.py
- temporalio/workflow.py
- tests/worker/test_interceptor.py
Fixes https://github.com/temporalio/sdk-python/issues/720
> Add workflow.instance() API for obtaining current workflow instance

- temporalio/client.py
- temporalio/converter.py
- tests/test_client.py
- tests/worker/test_workflow.py
Fixes https://github.com/temporalio/sdk-python/issues/594
Support updating schedule SAs. The API is that the user sets typed SAs in the same "updater" function that they use for updating the schedule itself.
> Update schedule search attributes

- README.md
- poetry.lock
- pyproject.toml
- temporalio/contrib/pydantic.py
- temporalio/converter.py
- temporalio/worker/workflow_sandbox/_restrictions.py
- tests/contrib/pydantic/activities.py
- tests/contrib/pydantic/models.py
- tests/contrib/pydantic/models_2.py
- tests/contrib/pydantic/test_pydantic.py
- tests/contrib/pydantic/workflows.py
- tests/contrib/test_pydantic.py
- tests/worker/workflow_sandbox/test_restrictions.py
- tests/worker/workflow_sandbox/test_runner.py
Fixes https://github.com/temporalio/sdk-python/issues/621, https://github.com/temporalio/sdk-python/issues/496
- Provide official pydantic support in a new module `temporalio.contrib.pydantic`.
- This support is based on `v2`, but we do retain the existing code that should allow `v1` to still be used.
- Due to our wrapping of the `datetime.datetime` class, and `datetime.datetime` instances, with proxy objects, we have to unwrap proxied objects to allow pydantic to work correctly.
See also https://github.com/temporalio/sdk-python/issues/627, https://github.com/temporalio/sdk-python/issues/207
TODO:
Accompanying samples PR: https://github.com/temporalio/samples-python/pull/163
> Pydantic contrib module

- .github/workflows/ci.yml
- README.md
- tests/worker/test_activity.py
- tests/worker/test_workflow.py
> Evolve observability documentation

- temporalio/client.py
- tests/worker/test_update_with_start.py
DWISOTT, fixes bug
1. Closes #791 
Added small integration test, mock RPC error using an interceptor.
No
> Check for grpc status details before indexing & unpacking

- tests/worker/test_update_with_start.py
Prevent error ouptut from test. See https://github.com/temporalio/sdk-python/pull/801#discussion_r2017485617
```
tests/worker/test_update_with_start.py .
================================================================================================= 1 passed in 0.54s ==================================================================================================
Future exception was never retrieved
future: <Future finished exception=RPCError('empty details')>
Traceback (most recent call last):
File "/Users/dan/src/temporalio/sdk-python/tests/worker/test_update_with_start.py", line 843, in test_start_update_with_start_empty_details
await client.start_update_with_start_workflow(
File "/Users/dan/src/temporalio/sdk-python/temporalio/client.py", line 1048, in …
```
> Prevent error output from passing test

- temporalio/client.py
- temporalio/worker/_workflow.py
- temporalio/worker/workflow_sandbox/_runner.py
- temporalio/workflow.py
- tests/helpers/__init__.py
- tests/test_client.py
- tests/worker/test_workflow.py
Expose root workflow execution to workflow info (available from workflow info) and workflow execution info (available from workflow describe/list)
1. Closes #774
Updating existing info,describe,list tests.
Probably
> Expose root workflow execution

- .github/workflows/ci.yml
- tests/__init__.py
- tests/conftest.py
- tests/contrib/test_opentelemetry.py
- tests/test_client.py
- tests/test_workflow.py
- tests/testing/test_workflow.py
- tests/worker/test_activity.py
- tests/worker/test_interceptor.py
- tests/worker/test_replayer.py
- tests/worker/test_update_with_start.py
- tests/worker/test_worker.py
- tests/worker/test_workflow.py
- tests/worker/workflow_sandbox/test_runner.py
* Added GH timeouts for entire workflow and for specific test runs
* Set macos intel to use 3.13.2 instead of default 3.13 (which is 3.13.3) because the newest released last week was failing, see #834
* Moved all dev servers to `v1.3.1-persistence-fix.0` version of CLI dev server to get https://github.com/temporalio/cli/pull/784
* macOS on 3.9, like Windows, rarely had a failure exit code post pytest-success, so we enabled same code as Windows to allow it to succeed. We believe this is caused by #300.
* In Python 3.9 still got import errors triggered by CPython bug https://github.com/python/cpython/issues/91351 when importing pytest into sandbox, so we pass through pytest imports in tests
There are still flakes, such as #300 and some server side persistence failures we are investigating. …
> [IGNORE] Improve test flakes

- temporalio/converter.py
- tests/test_converter.py
Before this PR, workflows and activities could not return dicts with non-string keys. E.g. something as simple as this fails:
```python
@workflow.run
async def run(self, name: str) -> dict[int, str]:
return {1: "a"}
```
```
TypeError: Failed converting key 1 on dict[int, str]
```
This is surprising to users because a pervasive feature of the Python SDK is that type annotations are used to make the data converter do the right thing: the type annotation should be "honored" there.
The behavior happens because (1) we default to json/plain encoding, (2) in JSON keys must be strings, (3) the Python JSON encoder accepts str, int, float, bool, None dict keys, silently encoding them as valid JSON string representations, (4) although the type annotation is typically present (either from a type …
> Data converter non-string keys

- temporalio/bridge/src/worker.rs
- temporalio/bridge/worker.py
- temporalio/worker/__init__.py
- temporalio/worker/_replayer.py
- temporalio/worker/_worker.py
- tests/worker/test_worker.py
Requires https://github.com/temporalio/sdk-python/pull/821 to merge first
Expose options to opt-in to new poller autoscaling behavior
1. Closes 
Added simple test. More meaningful tests are in Core, we just need to make sure option is passed properly here.
> Expose poller autoscaling options

- .github/workflows/build-binaries.yml
> Fix protobuf version in build-binaries wheel test

- temporalio/worker/_workflow.py
- temporalio/worker/_workflow_instance.py
- temporalio/workflow.py
- tests/worker/test_worker.py
- tests/worker/test_workflow.py
Added `@workflow.dynamic_config` function which can be used on dynamic workflows to specify per-type overrides to `@workflow.defn` settings.
Feature parity w/ Java for workflow versioning 
1. Closes 
Added tests
> Add dynamic config function

- temporalio/bridge/src/worker.rs
- temporalio/bridge/worker.py
- temporalio/worker/_replayer.py
- temporalio/worker/_worker.py
- tests/conftest.py
Fixes bug which was causing v2 versioning to be broken. Also fixes wrong dynamic config causing test to get skipped.
> Fix incorrectly set legacy build id options

- temporalio/worker/_workflow_instance.py
- temporalio/workflow.py
- tests/worker/test_workflow.py
Added `workflow.upsert_memo` function to support memo upsert functionality.
Feature request: https://github.com/temporalio/features/issues/119
1. Closes #190
Modified `test_workflow_memo` to also test upsert operation.
> Upsert memo support

- temporalio/converter.py
- tests/test_converter.py
Fixed the converter so that both `typing.Literal` and `typing_extensions.Literal` type hints are handled correctly. Previously only `typing_extensions.Literal` worked as expected.
1. Closes #852 
`tests/test_converter.py::test_json_type_hints` was updated with new checks.
No
> Fixed serialization of `typing.Literal`

- .vscode/settings.json
- temporalio/client.py
- tests/worker/test_workflow.py
Make static_details and static_summary lazy on the workflow description
Converting these fields can be expensive and is only necessary if the client requests these details. 
1. Closes #840 
Yes, breaking change in the API
> 💥 Breaking Change - Make static_details and static_summary lazy on the workflow description

- temporalio/worker/_interceptor.py
- temporalio/worker/_workflow_instance.py
- tests/helpers/__init__.py
Some minor cleanup pulled out of Nexus work.
> Minor cleanup

- temporalio/bridge/Cargo.lock
- temporalio/worker/_replayer.py
- temporalio/worker/_worker.py
- tests/worker/test_workflow.py
Updated core to obtain the fix for low (<2) WFT slot/poller counts causing workers to potentially get stuck.
This is a sorta-breaking change in that it makes a previously invalid configuration into a hard error at worker startup time.
> [Sorta-breaking] Update core to fix low wft slots/pollers issue

- temporalio/worker/_workflow_instance.py
- tests/worker/test_workflow.py
Instantiate interceptors later in workflow instance construction so that more variables are available.
Allows signal registration to work during interceptor creation
1. Closes #874
New workflow test
No
> Instantiate interceptors later in workflow instance construction

- temporalio/workflow.py
- tests/worker/test_workflow.py
Catch runtime error if asynio loop doesn't exist, returning False in `workflow.in_workflow`
Result of `workflow.in_workflow` should be available inside sync activities
1. Closes #878 
New workflow test
> Handle case where in_workflow is called in a synchronous activity

- README.md
Changed the readme to not lead with recommending async activities
There are many differing, great ideas on sync vs async activities, but I believe we at least don't want to explicitly lead with async.
Please modify as you see fit. This is just a proposal. Thanks as always 🙏
> Update README to not recommend async activities

- temporalio/bridge/worker.py
- tests/worker/test_workflow.py
Bug fix: when `codec.decode()` returns its input unchanged, the subsequent `metadata.clear()` accidentally cleared the new metadata contents.
> Fix memo payload metadata memory sharing bug

- pyproject.toml
- temporalio/contrib/openai_agents/README.md
- temporalio/service.py
- uv.lock
Bumping versions for `1.13` release
1. Closes 
> Update versions for release

- .github/workflows/ci.yml
Pin python version to 3.13.4 for windows-latest
3.13.5 introduced a linker error
1. Closes 
CI passes
> Pin windows python version to 3.13.4

- temporalio/worker/_workflow_instance.py
- tests/worker/test_workflow.py
Fail workflow upon ```pydantic.ValidationError``` when using the ```pydantic_data_converter```, so that the user can pass that specific exception type to ```workflow_failure_exception_types``` in order for the workflow to fail instead of keeping it running, since there is no way that such a workflow will ever complete with an incorrect payload.
1. Closes [[Feature Request] Fail workflow upon pydantic.ValidationError when using the pydantic_data_converter #815](https://github.com/temporalio/sdk-python/issues/815)
```tests/worker/test_workflow::test_workflow_fail_on_bad_input``` was updated to check the right exception message.
```test/worker/test_workflow::test_workflow_fail_on_bad_pydantic_input``` was added to check that the workflow indeed fails when a Pydantic …
> Do not wrap workflow-failure exceptions from converters in workflows

- README.md
Improve sandbox documentation, in particular relating to dataclasses and Pydantic models as a result of discussion in https://temporalio.slack.com/archives/CTT84RS0P/p1749927322488079.
> Evolve sandbox documentation

- temporalio/worker/_activity.py
- Behavior change: return exceptions instead of raising in `wait_all_completed`
- Minor extension to refactoring done in https://github.com/temporalio/sdk-python/pull/860
> Activity worker:  refactoring part 2

- pyproject.toml
- temporalio/contrib/openai_agents/invoke_model_activity.py
- tests/contrib/test_openai.py
- uv.lock
Include `eval-type-backport` when using OpenAI, fix a few type imports, unblock tests
The integration should work on all applicable python versions
1. Closes #914 
> Fixing issues with openai integration on python 3.9

- temporalio/worker/_nexus.py
- tests/nexus/test_workflow_caller_error_chains.py
Inject an additional error into the cause chain to work around the fact that `HandlerError` is an independent exception with its own error message and stack trace (unlike Go and Java).
> Nexus error chain workaround

- pyproject.toml
A change of this sort (modulo the exact set of exclusions we make) is essentially forced on us by Cursor's switch to https://github.com/DetachHead/basedpyright, which AFAIK defaults to  reporting every type checking error category. The set added here are ones that I've found to be essential given the current state and conventions in our codebase.
However, I think that this is a good direction, independently of Cursor: by explicitly specifying the subset of Pyright diagnostics that we support, we should be able to get to the position where the type-checking requirements made by our CI exactly match those made by our IDE.
> Set supported pyright diagnostics explicitly in pyproject.toml

- temporalio/contrib/openai_agents/temporal_openai_agents.py
- tests/contrib/openai_agents/test_openai.py
Add a Nexus operation version of `activity_as_tool`.
> nexus_operation_as_tool

- .github/workflows/build-binaries.yml
- pyproject.toml
- temporalio/nexus/_decorators.py
- temporalio/nexus/_util.py
- temporalio/worker/_interceptor.py
- temporalio/workflow.py
- tests/nexus/test_dynamic_creation_of_user_handler_classes.py
- tests/nexus/test_handler.py
- tests/nexus/test_handler_operation_definitions.py
- tests/nexus/test_workflow_caller.py
- uv.lock
- We want to develop the nexus SDK and respond to those upstream changes in the temporal SDK
- But currently the nexus SDK is not pinned in the temporal SDK, so we must not release breaking to nexus SDK, since temporal SDK installations in the wild would pick up an incompatible nexus SDK 
- And yet if we were to pin nexus SDK and release temporal SDK, then we wouldn't be able to release bug fixes to nexus SDK by simply releasing nexus SDK
- Pin unreleased temporal SDK to unreleased current `main` of nexus SDK
- Also break `build-binaries` so that we do not accidentally release temporal SDK in this state
- In order to release Temporal SDK, remove the pin-to-GitHub and remove the deliberate breakage of build-binaries, and reinstate them afterwards when next wanting to update the nexus SDK.
> Install nexusrpc from GitHub

- README.md
[rendered](https://github.com/temporalio/sdk-python/blob/document-client-worker-interceptors/README.md#interceptors)
> Add documentation of interceptors to README

- README.md
- temporalio/activity.py
- temporalio/testing/_activity.py
- temporalio/worker/_activity.py
- temporalio/worker/_worker.py
- tests/testing/test_activity.py
- tests/worker/test_activity.py
Fixes https://github.com/temporalio/sdk-python/issues/721
> Provide client in activity context

- temporalio/contrib/openai_agents/_invoke_model_activity.py
- temporalio/contrib/openai_agents/_openai_runner.py
If a tool is provided to an `Agent` that is not a tool type, raise an early exception. 
This can happen easily if a user passes an activity without wrapping in `activity_as_tool`
1. Closes 
> Add argument validation for the types of provided tools

- temporalio/contrib/openai_agents/_openai_runner.py
> Fail if user provides mcp servers

- temporalio/contrib/openai_agents/_openai_runner.py
- tests/contrib/openai_agents/test_openai.py
> Disallow use of sqlite sessions, but pass through others

- README.md
- temporalio/client.py
- temporalio/contrib/openai_agents/_temporal_openai_agents.py
- temporalio/worker/__init__.py
- temporalio/worker/_plugin.py
- temporalio/worker/_replayer.py
- temporalio/worker/_worker.py
- temporalio/worker/workflow_sandbox/_importer.py
- tests/contrib/openai_agents/test_openai_replay.py
- tests/test_plugins.py
Added ability to configure replayer to plugins. Plugins as a whole have become abstract so that plugin authors need to consider the different components they may need to configure.
1. Closes #994 
> :boom: Replayer configuration from plugins

- temporalio/nexus/_decorators.py
- temporalio/nexus/_operation_handlers.py
Remove unused parameters from `WorkflowRunOperationHandler`. It's not yet publicly exposed so there's no backwards-incompatibility impact.
> Nexus: eliminate unused arguments

- temporalio/envconfig.py
- tests/test_envconfig.py
Remove check for `address` in config. Allows for users to call `to_client_connect_config` and override this value themselves. The `Client.connect` call already does this validation for us.
Makes it easy in the general case where users just want to do:
```
config = ClientConfig.load_client_connect_config()
config.setdefault("target_host", "localhost:7233")
Client.connect(**config)
```
No tests
No
> remove address check

- temporalio/client.py
- temporalio/nexus/__init__.py
- temporalio/nexus/_decorators.py
- temporalio/nexus/_link_conversion.py
- temporalio/nexus/_operation_context.py
- temporalio/nexus/_operation_handlers.py
- temporalio/nexus/_token.py
On main, a circular import error is revealed by doing e.g.
```
uv run tests/nexus/test_type_checking.py
Traceback (most recent call last):
File "/Users/dan/src/temporalio/sdk-python/tests/nexus/test_type_checking.py", line 3, in <module>
import temporalio.nexus
File "/Users/dan/src/temporalio/sdk-python/temporalio/nexus/__init__.py", line 9, in <module>
from ._decorators import workflow_run_operation as workflow_run_operation
File "/Users/dan/src/temporalio/sdk-python/temporalio/nexus/_decorators.py", line 19, in <module>
from temporalio.nexus._operation_context import (
File "/Users/dan/src/temporalio/sdk-python/temporalio/nexus/_operation_context.py", line 22, in <module>
import temporalio.client
File "/Users/dan/src/temporalio/sdk-python/temporalio/client.py", line 60, in <module> …
```
> Fix circular import: do not import temporalio.client in temporalio.nexus

- temporalio/common.py
Making sure this is consistently optional everywhere
> Priority Key None by default

- temporalio/worker/_interceptor.py
- temporalio/worker/_workflow_instance.py
- temporalio/workflow.py
- tests/conftest.py
- tests/helpers/__init__.py
- tests/nexus/test_workflow_caller_cancellation_types.py
- tests/nexus/test_workflow_caller_cancellation_types_when_cancel_handler_fails.py
Implements cancellation types for Python Nexus. This PR is mainly tests. These provide coverage for the state machine changes in https://github.com/temporalio/sdk-core/pull/977. See https://github.com/temporalio/sdk-core/issues/911#issuecomment-3151904819
The gist for anyone who needs a refresher is:
- `Abandon` - caller workflow never even send a request cancel command. The state machine is such that the operation handle future is resolved with a cancellation exception in a second activation in the same WFT
- `TryCancel` - same as `Abandon` regarding the immediate resolution of the future, but do emit the cancel nexus op request command (maybe it could also have been called RequestAsync or something)
For the next two, one has to keep two concepts clearly distinct: the Nexus cancel …
> Nexus cancellation types

- temporalio/worker/_nexus.py
- tests/nexus/test_workflow_caller_errors.py
Convert `WorkflowAlreadyStartedError` to non-retryable `nexusrpc.HandlerError`.
> Python Nexus convert workflow start errors to Nexus errors

- tests/worker/test_interceptor.py
> Test workflow outbound nexus interception

- temporalio/converter.py
- tests/test_converter.py
Check for newtype before calling `isinstance`.
`isinstance` fails when the `key_type` is not a type.
1. Closes part of #1032
New tests
> Don't fail on newtype string dict keys

- temporalio/workflow.py
Fix the return type, and improve the comments inherited from Python a bit more.
> Fix return type of workflow.wait

- temporalio/client.py
- temporalio/service.py
Just some minor cleanup commits I have lying around.
> Minor edits and code cleanup

- temporalio/contrib/pydantic.py
- tests/contrib/openai_agents/test_openai.py
> Add a test for output type coercion

- temporalio/contrib/openai_agents/__init__.py
- temporalio/contrib/openai_agents/_temporal_openai_agents.py
Title
Users may need to include a codec with OpenAI functionality
1. Closes #1084 
> Only set payload converter, fail if already set

- temporalio/bridge/src/worker.rs
- temporalio/bridge/worker.py
- temporalio/worker/__init__.py
- temporalio/worker/_replayer.py
- temporalio/worker/_tuning.py
- temporalio/worker/_worker.py
- tests/worker/test_worker.py
- Add support for nexus in WorkerTuner and support `max_concurrent_nexus_tasks` worker config option
- Add tests for nexus worker concurrency parameters
💥 This is a breaking change: `create_composite()` has gained a required `nexus_supplier` parameter.
> 💥  Nexus support in worker tuner

- temporalio/contrib/openai_agents/README.md
- temporalio/contrib/openai_agents/_temporal_openai_agents.py
- tests/contrib/openai_agents/test_openai.py
> Rename mcp_servers to mcp_server_providers

- temporalio/contrib/openai_agents/_temporal_openai_agents.py
Title
Allows for setting up multiple workers for OpenAI Agents use, some of which will run model activities, and others which will run workflows.
1. Closes 
> Provide option to disable activity registration in OpenAI plugin

- .github/workflows/ci.yml
- pyproject.toml
- scripts/_proto/Dockerfile
- scripts/gen_payload_visitor.py
- scripts/gen_protos_docker.py
Title
This moves the calls to generate source out of the gen-protos-docker script and instead rely on poe tasks to align CI with local development.
> Move visitor, bridge client generation, and formatting to poe tasks
