temporalio/sdk-python

pyproject.toml
tests/worker/test_workflow.py

Updated version for impending release

Update version for 0.1a2 release

---

temporalio/__init__.py
temporalio/bridge/client.py
temporalio/workflow_service.py
tests/test_workflow_service.py

Added `__version__` for use by client to Temporal server
1. Closes #47

Add proper version to client

---

.github/workflows/ci.yml
README.md
pyproject.toml
temporalio/workflow_service.py

Update version and add minor note to README
Beta release

Update version to 0.1b1

---

scripts/fix_wheel.py

* Changed fix-wheel script to use `wheel` `pack`/`unpack` to keep checksums right
* Changed fix-wheel script to put proper macOS tags for ARM builds

Fixes for fix-wheel script

---

scripts/fix_wheel.py

Need to have fix-wheel fix multiple tags in WHEEL file
#97 changed the script but didn't account for multiple tags

Support multiple tags in fix-wheel

---

pyproject.toml
temporalio/service.py

Update version to 0.1b2
For release

Update version to 0.1b2

---

.github/workflows/ci.yml

If this works after merging, we can update the DNS.

Move API reference site to Vercel

---

tests/test_converter.py

Add possibly missing UUID test case
I was reading a test case and found missing slot
1. Closes: No issue was created
2. How was this tested: With unit test
3. Any docs updates needed? No

Add missing UUID test case

---

README.md
pyproject.toml
temporalio/service.py

* Update version to `0.1b3` for beta 3
* Add clarification on workflow exceptions

Bump version and workflow exception clarification

---

pyproject.toml
temporalio/service.py

Release 0.1b4

---

README.md
pyproject.toml
temporalio/service.py

Update version and remove beta README warning

Release 1.0.0

---

README.md
temporalio/workflow.py

Update docs to mark local activities as experimental
1. Closes #246

Mark local activities as experimental

---

pyproject.toml
temporalio/service.py

Update release version to `1.1.0`

Set release version as 1.1.0

---

pyproject.toml
temporalio/service.py

Prepare for 1.3.0 release. Won't be merged and happen until at least next week, but this gets it approved so I won't have to wait on approvers.

Update release version to 1.3.0

---

pyproject.toml
temporalio/runtime.py
temporalio/service.py

* Update release version to 1.4.0
* Mark log forwarding experimental pending resolution of [this thread](https://github.com/temporalio/sdk-python/pull/413#discussion_r1383697341)

Update release version to 1.4.0 and mark log forwarding experimental

---

pyproject.toml
temporalio/service.py

Update version to 1.5.0

---

pyproject.toml
temporalio/service.py

Update release version to 1.6.0

Update version to 1.6.0

---

tests/worker/test_workflow.py

Issue with a test where update wasn't getting to server before starting workflow. We now check the update is present on the server before starting the worker that processes both.

Fix flaky update test

---

.github/workflows/build-binaries.yml
.github/workflows/ci.yml

Use GH ARM runner
1. Closes #565

Use GH ARM runner

---

temporalio/client.py

Fixes #590
This change has no accompanying test.

Change client-side default to match server-side default

---

README.md

Update and edit signal and update handler documentation in the README.

Update documentation of signal and update handlers

---

tests/worker/test_workflow.py

With latest server, if a workflow completes when an update is in accepted state, that is now an `WorkflowUpdateFailedError` with cause an `ApplicationError` with type `"AcceptedUpdateCompletedWorkflow"`. Previously it was a NOT_FOUND gRPC error.

Respond to server changes to Update error

---

.github/workflows/ci.yml

Add VERCEL_PROJECT_ID and VERCEL_ORG_ID

---

pyproject.toml
temporalio/service.py
uv.lock

Bump version for 1.12.0 release

---

temporalio/contrib/openai_agents/model_parameters.py
temporalio/contrib/openai_agents/temporal_openai_agents.py

Set default model activity timeout to 60s

---

pyproject.toml
temporalio/service.py
uv.lock

Update version to 1.15.0

---

temporalio/contrib/openai_agents/README.md

Fix readme to work with plugins

---

.github/workflows/ci.yml

Extend test timeout to 15 minutes. Macos-intel is running over

---

pyproject.toml
temporalio/service.py
uv.lock

Update version to 1.18.0
